---
all:
  children:
    PVE:
      hosts:
        proxmox:
          ansible_host: 192.168.1.100
    LXC:
      hosts:
        LXC1:
          ansible_host: 192.168.1.102
        LXC2:
          ansible_host: 192.168.1.103
        LXC3:
          ansible_host: 192.168.1.104
        LXC4:
          ansible_host: 192.168.1.105
        LXC5:
          ansible_host: 192.168.1.106
        LXC6:
          ansible_host: 192.168.1.107
        LXC7:
          ansible_host: 192.168.1.108
        LXC8:
          ansible_host: 192.168.1.109
        LXC9:
          ansible_host: 192.168.1.110
        LXC_111:
          ansible_host: 192.168.1.111
        LXC_112:
          ansible_host: 192.168.1.112
        LXC_113:
          ansible_host: 192.168.1.113
        LXC_115:
          ansible_host: 192.168.1.115
        LXC_116:
          ansible_host: 192.168.1.116
        LXC_117:
          ansible_host: 192.168.1.117
        LXC_118:
          ansible_host: 192.168.1.118

    local:
      hosts:
        localhost:
          ansible_connection: local
