---
- name: Configure dotfiles for individual tools
  hosts: localhost
  roles:
    # Ditch alacritty for ghostty. It's been acting weird lately with completion
    # borders and all especially in (md) files.
    # - alacritty

    - role: common
      tags: [dotfiles]
