---
- name: Asegurar que los directorios de configuración existen
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "~/.config"
    - "~/.config/nvim"

- name: Aplicar configuración de ZSH (usando templates)
  ansible.builtin.template:
    src: zshrc.j2
    dest: ~/.zshrc
    mode: '0644'

- name: Aplicar configuración de Git
  ansible.builtin.template:
    src: gitconfig.j2
    dest: ~/.gitconfig
    mode: '0644'
