---
- name: Habilitar repositorio COPR atim/starship
  become: true
  ansible.builtin.command: dnf copr enable atim/starship -y
  changed_when: false

- name: Instalar Starship
  become: true
  ansible.builtin.package:
    name: starship
    state: present

- name: Asegurar que el directorio .config existe
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config"
    state: directory
    mode: '0755'

- name: Aplicar configuraci√≥n starship.toml
  ansible.builtin.copy:
    src: starship.toml
    dest: "{{ ansible_facts['user_dir'] }}/.config/starship.toml"
    mode: '0644'
